target-version = "py313"
line-length = 120
lint.preview = true
lint.select = [
    "ALL",
]
lint.ignore = [
    "COM812", # Conflicts with the formatter
    "CPY001", # Missing copyright notice
    "D200", # Conflicts with docformatter --make-summary-multi
]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
docstring-code-line-length = 80
indent-style = "space"
quote-style = "double"
